#PES Python Assignments SET 1
#19 Python program Basics
#Python program Basics	-
##Write a program to generate a Fibonacci series of numbers.
##Starting numbers are 0 and 1,  new number in the series is generated by adding previous two numbers in the series.
##Example : 0, 1, 1, 2, 3, 5, 8,13,21,.....
##   a) Number of elements printed in the series should be N numbers, Where N is any +ve integer.
##   b) Generate the series until the element in the series is less than Max number.




#Manoj Dixit - 20141404
#Python 3.9.0

i=int(input('Please enter N value for Fibonacci series : '))
f1=0
f2=1
print(f1,end=' ')
print(f2,end=' ')
count=0
while True:
    if (count+2)==i:
        break
    f2=f1+f2
    print(f2,end=' ')
    f1=f2-f1
    count+=1
    
    
##Result:
##    Please enter N value for Fibonacci series : 30
##    0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 
##    Please enter N value for Fibonacci series : 8
##    0 1 1 2 3 5 8 13 
